### ISSUE TITLE
Add e2e tests for external health monitor agent

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-health-monitor#35]

**Comment by NickrenREN** [comment]
Anyone who is interested in this ?

**Comment by irbekrm** [comment]
Hi! I would be interested in working on this issue.

**Comment by NickrenREN** [comment]
@irbekrm Thanks a lot

**Comment by xing-yang** [comment]
See my comment on https://github.com/kubernetes-csi/external-health-monitor/issues/34.  It is not reliable for an e2e test to depend on whether an event is recorded or not.
