### ISSUE TITLE
Release external-health-monitor to v0.1.1

### ISSUE THREAD

**Issue by fengzixu** [kubernetes-csi/external-health-monitor#44]
## Reason

When I integrated the external-health-monitor with host-path-driver, I found its release script to get the rbac yaml files of csi components based on image tag. Because external-health-monitor has been released as v0.1.0, it will take https://raw.githubusercontent.com/kubernetes-csi/external-health-monitor/v0.1.0/deploy/kubernetes/external-health-monitor-controller/rbac.yaml

But, there is a bug in rbac file of external-health-monitor-controller. It was fixed in this commit: https://github.com/kubernetes-csi/external-health-monitor/commit/78fb3857852a3930031b66dd69302d3e8f941b88#diff-4f92853217f76a2e31d2f601fcf8a532c199a96999ed40318cb2c6a93c7d9604L38

So, I want to do a new release for resolving the issue I encountered

**Comment by xing-yang** [comment]
0.2.0 is released.  Close this issue.
