### ISSUE TITLE
Record an event when an error occurs in the health monitoring controller and agent

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-health-monitor#52]
Currently an event will be recorded on pvc/pod when the controller/agent has successfully retrieved an abnormal volume condition from the storage system. However when other errors occur in the controller/agent, the errors will be logged but not recorded as events. Before moving to beta, the controller/agent should be modified to record an event when other errors occur.

**Comment by fengzixu** [comment]
You mean convert all errors happen in controller/agent to the event and let those events are forwarded to pod of controller/agent?

**Comment by fengzixu** [comment]
What's the error you want to record? error happens in communication between controller/agent and CSI-Driver?
