### ISSUE TITLE
include additional context in NodeGetVolumeStats method to help volume_condition logic

### ISSUE THREAD

**Issue by travisghansen** [kubernetes-csi/external-health-monitor#58]
I'd love to see the `readonly` attribute of the publish request passed into this method. A specific use-case I'm addressing is when an iscsi connection drops and then comes back online the mount becomes `ro` instead of `rw`. However without knowing specifically if it *supposed* to be `ro` I can for certain say if it's unhealthy or not.

In my case I support staging so on the same node it's theoretically possible (at least from a csi perspective...maybe not k8s) to have the same volume published in 1 case `ro` and another case `rw`. I support this by staging `rw` and then doing a bind mount with `ro` if appropriate. Not sure if the stats method gets called on the staged target or the published target but that could make the logic more complex.

Thanks!

**Comment by xing-yang** [comment]
We'll see if we can pass in ` VolumeCapability` in `NodeGetVolumeStatsRequest`.

**Comment by travisghansen** [comment]
I'm not sure that addresses the issue per-se. As a volume can advertise many capabilities and none of them necessarily directly equates to what was passed as the `readonly` flag during publish (indicated by the fact that indeed they are 2 distinct attributes of the request). Having said that, I'm sure including it would be helpful, just not sure it's enough.
