### ISSUE TITLE
Only watch Pods and Nodes when Node Watcher is enabled

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-health-monitor#75]
In the external-health-monitor-controller, we always watch all PVCs, Pods, Nodes:
https://github.com/kubernetes-csi/external-health-monitor/blob/v0.3.0/cmd/csi-external-health-monitor-controller/main.go#L210

We need to watch them to support the Node Watcher functionality which is disabled by default.  This has caused scalability problems.
https://github.com/kubernetes-csi/external-health-monitor/blob/v0.3.0/cmd/csi-external-health-monitor-controller/main.go#L66

We should change the code to only watch Pods and Nodes when the Node Watcher component is enabled.

https://github.com/kubernetes/kubernetes/issues/102452#issuecomment-856854322

**Comment by pohly** [comment]
It also would be useful to address the scalability issue when the Node Watcher functionality is enabled.
