### ISSUE TITLE
Mock ControllerGetVolume/NodeGetVolumeStats/ListVolumes RPCs to test controller/agent here

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes-csi/external-health-monitor#9]

**Comment by fengzixu** [comment]
Please assign to me

**Comment by NickrenREN** [comment]
@fengzixu You may need to add support in csi-test repo for volume health monitor.
Example: https://github.com/kubernetes-csi/csi-test/pull/160

**Comment by fengzixu** [comment]
Implementing

**Comment by fengzixu** [comment]
When I resolved this issue, I found the `GET_VOLUME_HEALTH` capability doesn't exist in spec repository. I think it was replaced by `GET_VOLUME_CONDITION`. Right? 

- KEP: https://github.com/kubernetes/enhancements/pull/1077/files#diff-077b91d1804a891f8b79c30eeaa4964fR187
- Spec: https://github.com/container-storage-interface/spec/pull/415/files#diff-41f1638f086beb93f65a22cf27bb8be2R219

And, I found the `ListVolumes` RPC interface has been mocked. https://github.com/kubernetes-csi/csi-test/blob/613e9285fbb8552aae5827286600146dff19db62/mock/service/controller.go#L329

**Comment by fengzixu** [comment]
Not sure if this PR can satisfy our mock requirement. Please check: https://github.com/kubernetes-csi/csi-test/pull/268

**Comment by xing-yang** [comment]
Yes, it is GET_VOLUME_CONDITION.

ListVolumes is an existing RPC.  We just added volume_condition in its response.

**Comment by xing-yang** [comment]
You can take a look of this PR to see what changes are added to CSI spec to support volume health: https://github.com/container-storage-interface/spec/pull/415
