### ISSUE TITLE
VolumePath  for Block PV is incorrect

### ISSUE THREAD

**Issue by scuzhanglei** [kubernetes-csi/external-health-monitor#92]
when use Block PV, this error would occur：
```shell
E0901 10:33:25.153213       1 server.go:110] GRPC error: rpc error: code = NotFound 
desc = Could not get file information
 from /var/lib/kubelet/pods/a38a090d-deb6-457b-be20-dd3d5be90fad/volumes/kubernetes.io~csi/pvc-16d05a9d-d67a-45d5-8ac6-7c06778a9150/mount: 
stat /var/lib/kubelet/pods/a38a090d-deb6-457b-be20-dd3d5be90fad/volumes/kubernetes.io~csi/pvc-16d05a9d-d67a-45d5-8ac6-7c06778a9150/mount:
 no such file or directory
```
This is caused by [CheckNodeVolumeStatus](https://github.com/kubernetes-csi/external-health-monitor/blob/34082d08dda115f6daafd05caf417a208e874b55/pkg/csi-handler/pv_checker.go#L206) only consider FileSystem PV, but Block PV have different path.

**Comment by fengzixu** [comment]
Hi @scuzhanglei , thank you for pointing out this issue. Could I know what's your block volume path?

**Comment by scuzhanglei** [comment]
@fengzixu I test it with [csi-driver-host-path](https://github.com/kubernetes-csi/csi-driver-host-path), the bug would occur for any driver with block PV.

**Comment by xing-yang** [comment]
@fengzixu Is this fixed with the new csi-driver-host-path code or do we need to fix it in external-health-monitor?  This is for raw block mode.
