### ISSUE TITLE
"ControllerGetVolume" reports "Not Found" is invalid  with local storage backend 

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/external-health-monitor#99]
Reproduce:
1. deploy the external-provisioner in election-leader mode and with replicatins >=2.
2. disable "ControllerListVolume"  capability in hostpath driver.
3. deploy the hostpath driver in daemonset.
3. use "ControllerGetVolume" to get volume'status.
4. deploy the healthe monitor sidecar with election-leader mode.
5. create pvc in the local.

Fix:
1. if the backend storage is local, we should filter the pv with node name. Only monitor the pv in the same node with the sidecar

Suggestion:
1. If backend storege is local disk, Not only "COntrollerGetVolume" or "ControllerListVolume"  should monitor  the local volume that with the monitor sidecar in the same node.

CC @xing-yang

**Comment by xing-yang** [comment]
@zhucan How many worker nodes have you deployed?
I don't understand your suggestion.  Can you answer the following questions?
- If backend storage is local disk, does "ControllerGetVolume" work?
- If backend storage is local disk, does "ListtVolumes" work?

**Comment by zhucan** [comment]
@xing-yang  If only "ControllerGetVolume"  enabled,  It will get the pv firstly and "GetVolume" from the local disk, but if the volume  not exist in the local node(in the other node), it will reports the volume is "Not Found". But the reports is invalid.

**Comment by xing-yang** [comment]
There's another issue opened to track this and there's already an WIP PR about it.
https://github.com/kubernetes-csi/external-health-monitor/issues/87

**Comment by xing-yang** [comment]
Hi @pohly, do you know if distributed external-provisioner works with CSI hostpath driver?  Do we have e2e tests for distributed mode using CSI hostpath driver?

**Comment by pohly** [comment]
Yes, it works.

There is a [separate deployment](https://github.com/kubernetes-csi/csi-driver-host-path/tree/master/deploy/kubernetes-distributed) and a [Prow job](https://github.com/kubernetes/test-infra/blob/1210da22fd95cc50cf95b8c0902313b79174c4d2/config/jobs/kubernetes-csi/csi-driver-host-path/csi-driver-host-path-manual-job-config.yaml#L4-L55) which uses that deployment.
